version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

artifacts:
  files:
    - target/alpha.war
  discard-paths: 'yes'

cache:
  paths:
    - /root/.m2/**/*
