version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y docker.io -y
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package
      - docker build . -t myapp
    finally:
      - echo This always runs even if the install command fails

artifacts:
  files:
    - target/alpha.war
  discard-paths: 'yes'

cache:
  paths:
    - /root/.m2/**/*